spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:h2:file:./h2
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
